name: CWClans
version: '1.0'
main: me.skellf.cwclans.CWClans
api-version: '1.20'
load: STARTUP
authors: [ skellf ]
description: Plugin for adding a clans mechanic on server
commands:
  clans:
    usage: /clans <create|reload>
    aliases: c
    description: Main command
permissions:
  cwclans.*:
    description: Permission for all commands
    default: op
    children:
      cwclans.createclan: true
  cwclans.createclan:
    description: Permission for using main command
